//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTracNghiemTiengAnhTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQua
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KetQua()
        {
            this.ChiTietKetQuas = new HashSet<ChiTietKetQua>();
        }
    
        public int Maketqua { get; set; }
        public string Username { get; set; }
        public Nullable<int> MaDe { get; set; }
        public Nullable<double> Diem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietKetQua> ChiTietKetQuas { get; set; }
        public virtual KyThi KyThi { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
