//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTracNghiemTiengAnhTHPT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TracNghiemTiengAnhTHPTEntities : DbContext
    {
        public TracNghiemTiengAnhTHPTEntities()
            : base("name=TracNghiemTiengAnhTHPTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaoLoi> BaoLois { get; set; }
        public virtual DbSet<CauHoi> CauHois { get; set; }
        public virtual DbSet<ChiTietKetQua> ChiTietKetQuas { get; set; }
        public virtual DbSet<DangBai> DangBais { get; set; }
        public virtual DbSet<DanhGia> DanhGias { get; set; }
        public virtual DbSet<KetQua> KetQuas { get; set; }
        public virtual DbSet<KyThi> KyThis { get; set; }
        public virtual DbSet<NhomCauHoi> NhomCauHois { get; set; }
        public virtual DbSet<PhongThi> PhongThis { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
        public virtual DbSet<LienHe> LienHes { get; set; }
    }
}
