//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTracNghiemTiengAnhTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_ChitietKyThi
    {
        public Nullable<int> SoCauHoi { get; set; }
        public Nullable<int> DiemTrungBinh { get; set; }
        public string MaDe { get; set; }
        public string TenKyThi { get; set; }
        public int ThoiGian { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public bool CongKhai { get; set; }
        public Nullable<int> Soluot { get; set; }
    }
}
